
import { Theme } from "@/theme/theme";
import { ThemeProvider } from "@mui/material";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "School Administrator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider theme={Theme}>
        <body className={inter.className} style={{
          margin: 0
        }}>
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
